export const PLANET_TO_CITY_MAP: Record<string, { city: string; country: string }> = {
  'Tatooine': { city: 'Lima', country: 'PE' },
  'Alderaan': { city: 'Montreal', country: 'CA' },
  'Yavin IV': { city: 'Quito', country: 'EC' },
  'Hoth': { city: 'Reykjavik', country: 'IS' },
  'Dagobah': { city: 'Manaus', country: 'BR' },
  'Bespin': { city: 'Denver', country: 'US' },
  'Endor': { city: 'Toronto', country: 'CA' },
  'Naboo': { city: 'Florence', country: 'IT' },
  'Coruscant': { city: 'New York', country: 'US' },
  'Kamino': { city: 'San José', country: 'CR' },
  'Geonosis': { city: 'Buenos Aires', country: 'AR' },
  'Utapau': { city: 'Valparaíso', country: 'CL' },
  'Mustafar': { city: 'Medellín', country: 'CO' },
  'Kashyyyk': { city: 'La Paz', country: 'BO' },
  'Polis Massa': { city: 'Santiago', country: 'CL' },
  'Mygeeto': { city: 'Oslo', country: 'NO' },
  'Felucia': { city: 'Cancún', country: 'MX' },
  'Cato Neimoidia': { city: 'Barcelona', country: 'ES' },
  'Saleucami': { city: 'Antigua', country: 'GT' },
  'Stewjon': { city: 'Cusco', country: 'PE' },
  'Eriadu': { city: 'Montevideo', country: 'UY' },
  'Corellia': { city: 'Chicago', country: 'US' },
  'Rodia': { city: 'Tijuana', country: 'MX' },
  'Nal Hutta': { city: 'São Paulo', country: 'BR' },
  'Dantooine': { city: 'San Salvador', country: 'SV' },
  'Bestine IV': { city: 'Porto', country: 'PT' },
  'Ord Mantell': { city: 'Philadelphia', country: 'US' },
  'unknown': { city: 'Punta Cana', country: 'DO' },
  'Trandosha': { city: 'Lyon', country: 'FR' },
  'Socorro': { city: 'Bogotá', country: 'CO' },
  'Mon Cala': { city: 'Panama City', country: 'PA' },
  'Chandrila': { city: 'Berlin', country: 'DE' },
  'Sullust': { city: 'Zagreb', country: 'HR' },
  'Toydaria': { city: 'Guadalajara', country: 'MX' },
  'Malastare': { city: 'Mérida', country: 'MX' },
  'Dathomir': { city: 'Pereira', country: 'CO' },
  'Ryloth': { city: 'Maracaibo', country: 'VE' },
  'Aleen Minor': { city: 'San Juan', country: 'PR' },
  'Vulpter': { city: 'Curitiba', country: 'BR' },
  'Troiken': { city: 'Trujillo', country: 'PE' },
  'Tund': { city: 'Tegucigalpa', country: 'HN' },
  'Haruun Kal': { city: 'Brussels', country: 'BE' },
  'Cerea': { city: 'Córdoba', country: 'AR' },
  'Glee Anselm': { city: 'Cali', country: 'CO' },
  'Iridonia': { city: 'Lodz', country: 'PL' },
  'Tholoth': { city: 'Salvador', country: 'BR' },
  'Iktotch': { city: 'Maceió', country: 'BR' },
  'Quermia': { city: 'Nice', country: 'FR' },
  'Dorin': { city: 'Naples', country: 'IT' },
  'Champala': { city: 'Havana', country: 'CU' },
  'Mirial': { city: 'Caracas', country: 'VE' },
  'Serenno': { city: 'Lisbon', country: 'PT' },
  'Concord Dawn': { city: 'Guatemala City', country: 'GT' },
  'Zolan': { city: 'Montecristi', country: 'EC' },
  'Ojom': { city: 'San Miguel', country: 'SV' },
  'Skako': { city: 'Port-au-Prince', country: 'HT' },
  'Muunilinst': { city: 'Barranquilla', country: 'CO' },
  'Shili': { city: 'Arequipa', country: 'PE' },
  'Kalee': { city: 'San José de Mayo', country: 'UY' },
  'Umbara': { city: 'Puno', country: 'PE' },
};
